function dydt = vaccine_odes_us2(t,y,v)
% Equations of the model with vaccination rate v

global w p1 beta1 beta2 delta1 gamrec1 beta3 beta4 gamrec2 q alpha epsilona epsilonla epsilonlb delta2 eta

S=y(1);
E=y(2);
I=y(3);
A=y(4);
V=y(5);
EU=y(6);
IU=y(7);
AU=y(8);
D=y(9);
R=y(10);


dS_dt =- beta1*S.*I./(S+E+I+A+V+EU+IU+AU+D+R) ...
        - beta2*S.*A./(S+E+I+A+V+EU+IU+AU+D+R) -beta3*S.*IU./(S+E+I+A+V+EU+IU+AU+D+R) ...
        - beta4*S.*AU./(S+E+I+A+V+EU+IU+AU+D+R) + alpha*V ...
    -(1-epsilona)*v(t)*S + eta*R;
dE_dt= beta1*S.*I./(S+E+I+A+V+EU+IU+AU+D+R) ...
        + beta2*S.*A./(S+E+I+A+V+EU+IU+AU+D+R)... 
        + (1-epsilonla)*beta1*I*V./(S+E+I+A+V+EU+IU+AU+D+R) ... 
        + (1-epsilonla)*beta2*A*V./(S+E+I+A+V+EU+IU+AU+D+R)  -w*E;                % Exposed
dI_dt = p1*w*E - delta1*I - gamrec1*I;                                       % Symptomatic
dA_dt = (1-p1)*w*E - gamrec1*A;                                              % Asymptomatic
dV_dt = (1-epsilona)*v(t)*S...
          - (1-epsilonla)*beta1*I*V./(S+E+I+A+V+EU+IU+AU+D+R) ... 
      - (1-epsilonla)*beta2*A*V./(S+E+I+A+V+EU+IU+AU+D+R) ...
    - alpha*V ...
    -(1-epsilonlb)*beta3*V.*IU./(S+E+I+A+V+EU+IU+AU+D+R) ...
    -(1-epsilonlb)*beta4*V.*AU./(S+E+I+A+V+EU+IU+AU+D+R);                                                        % Vaccinated

dEU_dt = + beta3*S.*IU./(S+E+I+A+V+EU+IU+AU+D+R) ...
        + beta4*S.*AU./(S+E+I+A+V+EU+IU+AU+D+R) ... 
        +(1-epsilonlb)*beta3*V.*IU./(S+E+I+A+V+EU+IU+AU+D+R) ...
    +(1-epsilonlb)*beta4*V.*AU./(S+E+I+A+V+EU+IU+AU+D+R)...
    +beta3*R.*IU./(S+E+I+A+V+EU+IU+AU+D+R)...
    +beta4*R.*AU./(S+E+I+A+V+EU+IU+AU+D+R)- w*EU;    % Exposed Second variant
dIU_dt = q*w*EU - delta2*IU - gamrec2*IU;                                   % Symptomatic vaccinated
dAU_dt = (1-q)*w*EU - gamrec2*AU;                                           % Asymptomatic vaccinated
dD_dt = delta1*I + delta2*IU;  
dR_dt= gamrec1*(I+A)+ gamrec2*(IU+AU)-eta*R...
-beta3*R.*IU./(S+E+I+A+V+EU+IU+AU+D+R)-beta4*R.*AU./(S+E+I+A+V+EU+IU+AU+D+R);% Recovered

dydt = [dS_dt; dE_dt; dI_dt; dA_dt; dV_dt; dEU_dt; dIU_dt; dAU_dt; dD_dt; dR_dt];

end